version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Batmanlol1
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sqlserver_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ''Batmanlol1'' -Q "SELECT 1"',
        ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqlserver_data:
    driver: local

networks:
  sqlserver_network:
    driver: bridge
